-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 19:29:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gabriel_micillo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gabriel_micillo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gabriel_micillo` DEFAULT CHARACTER SET UTF8MB4 ;
USE `gabriel_micillo` ;

-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exp_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Financiations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Financiations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fin_origin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Labs_Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Labs_Size` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lab_size` VARCHAR(45) NOT NULL,
  `square_meters` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Laboratories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Laboratories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `exp_capacity` INT NOT NULL,
  `labs_size_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`, `labs_size_id`, `city_id`),
  INDEX `fk_Laboratories_Labs_Size1_idx` (`labs_size_id` ASC) VISIBLE,
  INDEX `fk_Laboratories_Cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_Laboratories_Labs_Size1`
    FOREIGN KEY (`labs_size_id`)
    REFERENCES `gabriel_micillo`.`Labs_Size` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Laboratories_Cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `gabriel_micillo`.`Cities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Costs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Costs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cost_per_hour` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `type_id`),
  INDEX `fk_Costs_Types1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Costs_Types1`
    FOREIGN KEY (`type_id`)
    REFERENCES `gabriel_micillo`.`Types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hours_required` INT NOT NULL,
  `cost_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cost_id`),
  INDEX `fk_Orders_Costs1_idx` (`cost_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Costs1`
    FOREIGN KEY (`cost_id`)
    REFERENCES `gabriel_micillo`.`Costs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Experiments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Experiments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test_tube_usage` INT NOT NULL,
  `status_id` INT NOT NULL,
  `types_id` INT NOT NULL,
  `financiations_id` INT NOT NULL,
  `lab_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`, `status_id`, `types_id`, `financiations_id`, `lab_id`, `order_id`),
  INDEX `fk_Experiments_Status_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_Experiments_Types1_idx` (`types_id` ASC) VISIBLE,
  INDEX `fk_Experiments_Financiations1_idx` (`financiations_id` ASC) VISIBLE,
  INDEX `fk_Experiments_Laboratories1_idx` (`lab_id` ASC) VISIBLE,
  INDEX `fk_Experiments_Orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Experiments_Status`
    FOREIGN KEY (`status_id`)
    REFERENCES `gabriel_micillo`.`Status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Experiments_Types1`
    FOREIGN KEY (`types_id`)
    REFERENCES `gabriel_micillo`.`Types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Experiments_Financiations1`
    FOREIGN KEY (`financiations_id`)
    REFERENCES `gabriel_micillo`.`Financiations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Experiments_Laboratories1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `gabriel_micillo`.`Laboratories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Experiments_Orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `gabriel_micillo`.`Orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Phone_Numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Phone_Numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` INT NOT NULL,
  `lab_id` INT NOT NULL,
  PRIMARY KEY (`id`, `lab_id`),
  INDEX `fk_Phone_Numbers_Laboratories1_idx` (`lab_id` ASC) VISIBLE,
  CONSTRAINT `fk_Phone_Numbers_Laboratories1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `gabriel_micillo`.`Laboratories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position_id` INT NOT NULL,
  PRIMARY KEY (`id`, `position_id`),
  INDEX `fk_Employees_Positions1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Positions1`
    FOREIGN KEY (`position_id`)
    REFERENCES `gabriel_micillo`.`Positions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gabriel_micillo`.`Weekly_Shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gabriel_micillo`.`Weekly_Shifts` (
  `lab_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `weekly_shifts` INT NOT NULL,
  PRIMARY KEY (`lab_id`, `employee_id`),
  INDEX `fk_Laboratories_has_Employees_Employees1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_Laboratories_has_Employees_Laboratories1_idx` (`lab_id` ASC) VISIBLE,
  CONSTRAINT `fk_Laboratories_has_Employees_Laboratories1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `gabriel_micillo`.`Laboratories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Laboratories_has_Employees_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `gabriel_micillo`.`Employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
